export const GET_LIST_OF_CLUB_ACTION = 'app/GET_LIST_OF_CLUB_ACTION'
export const GET_LIST_OF_CLUB = 'app/GET_LIST_OF_CLUB'
export const GET_LIST_OF_CLUB_SUCCES = 'app/GET_LIST_OF_CLUB_SUCCES'
export const GET_LIST_OF_CLUB_FAIL = 'app/GET_LIST_OF_CLUB_FAIL'

export const GET_LIST_OF_PLAYERS_ACTION = 'app/GET_LIST_OF_PLAYERS_ACTION'
export const GET_LIST_OF_PLAYERS = 'app/GET_LIST_OF_PLAYERS'
export const GET_LIST_OF_PLAYERS_SUCCES = 'app/GET_LIST_OF_PLAYERS_SUCCES'
export const GET_LIST_OF_PLAYERS_FAIL = 'app/GET_LIST_OF_PLAYERS_FAIL'



export const GET_LIST_OF_PLAYER_BY_ID_ACTION = 'app/GET_LIST_OF_PLAYER_BY_ID_ACTION'
export const GET_LIST_OF_PLAYER_BY_ID = 'app/GET_LIST_OF_PLAYER_BY_ID'

